export const langs = [
  { name: "Afrikaans", value: "af-ZA" },
  { name: "Bahasa Indonesia", value: "id-ID" },
  { name: "Bahasa Melayu", value: "ms-MY" },
  { name: "Català", value: "ca-ES" },
  { name: "Čeština", value: "cs-CZ" },
  { name: "Deutsch", value: "de-DE" },
  { name: "English - Australia", value: "en-AU" },
  { name: "English - Canada", value: "en-CA" },
  { name: "English - India", value: "en-IN" },
  { name: "English - New Zealand", value: "en-NZ" },
  { name: "English - South Africa", value: "en-ZA" },
  { name: "English - United Kingdom", value: "en-GB" },
  { name: "English - United States", value: "en-US" },
  { name: "Español - Argentina", value: "es-AR" },
  { name: "Español - Bolivia", value: "es-BO" },
  { name: "Español - Chile", value: "es-CL" },
  { name: "Español - Colombia", value: "es-CO" },
  { name: "Español - Costa Rica", value: "es-CR" },
  { name: "Español - Ecuador", value: "es-EC" },
  { name: "Español - El Salvador", value: "es-SV" },
  { name: "Español - España", value: "es-ES" },
  { name: "Español - Estados Unidos", value: "es-US" },
  { name: "Español - Guatemala", value: "es-GT" },
  { name: "Español - Honduras", value: "es-HN" },
  { name: "Español - México", value: "es-MX" },
  { name: "Español - Nicaragua", value: "es-NI" },
  { name: "Español - Panamá", value: "es-PA" },
  { name: "Español - Paraguay", value: "es-PY" },
  { name: "Español - Perú", value: "es-PE" },
  { name: "Español - Puerto Rico", value: "es-PR" },
  { name: "Español - República Dominicana", value: "es-DO" },
  { name: "Español - Uruguay", value: "es-UY" },
  { name: "Español - Venezuela", value: "es-VE" },
  { name: "Euskara", value: "eu-ES" },
  { name: "Français", value: "fr-FR" },
  { name: "Galego", value: "gl-ES" },
  { name: "Hrvatski", value: "hr_HR" },
  { name: "IsiZulu", value: "zu-ZA" },
  { name: "Íslenska", value: "is-IS" },
  { name: "Italiano - Italia", value: "it-IT" },
  { name: "Italiano - Svizzera", value: "it-CH" },
  { name: "Magyar", value: "hu-HU" },
  { name: "Nederlands", value: "nl-NL" },
  { name: "Norsk bokmål", value: "nb-NO" },
  { name: "Polski", value: "pl-PL" },
  { name: "Português - Brasil", value: "pt-BR" },
  { name: "Português - Portugal", value: "pt-PT" },
  { name: "Română", value: "ro-RO" },
  { name: "Slovenčina", value: "sk-SK" },
  { name: "Suomi", value: "fi-FI" },
  { name: "Svenska", value: "sv-SE" },
  { name: "Türkçe", value: "tr-TR" },
  { name: "български", value: "bg-BG" },
  { name: "Pусский", value: "ru-RU" },
  { name: "Српски", value: "sr-RS" },
  { name: "한국어", value: "ko-KR" },
  { name: "中文 - 普通话 (中国大陆)", value: "cmn-Hans-CN" },
  { name: "中文 - 普通话 (香港)", value: "cmn-Hans-HK" },
  { name: "中文 - 中文 (台灣)", value: "cmn-Hant-TW" },
  { name: "中文 - 粵語 (香港)", value: "yue-Hant-HK" },
  { name: "日本語", value: "ja-JP" },
  { name: "Lingua latīna", value: "la" },
]
