export const langs = [
  { value: "af-ZA", name: "Afrikaans" },
  { value: "id-ID", name: "Bahasa Indonesia" },
  { value: "ms-MY", name: "Bahasa Melayu" },
  { value: "ca-ES", name: "Català" },
  { value: "cs-CZ", name: "Čeština" },
  { value: "de-DE", name: "Deutsch" },
  { value: "en-AU", name: "English - Australia" },
  { value: "en-CA", name: "English - Canada" },
  { value: "en-IN", name: "English - India" },
  { value: "en-NZ", name: "English - New Zealand" },
  { value: "en-ZA", name: "English - South Africa" },
  { value: "en-GB", name: "English - United Kingdom" },
  { value: "en-US", name: "English - United States" },
  { value: "es-AR", name: "Español - Argentina" },
  { value: "es-BO", name: "Español - Bolivia" },
  { value: "es-CL", name: "Español - Chile" },
  { value: "es-CO", name: "Español - Colombia" },
  { value: "es-CR", name: "Español - Costa Rica" },
  { value: "es-EC", name: "Español - Ecuador" },
  { value: "es-SV", name: "Español - El Salvador" },
  { value: "es-ES", name: "Español - España" },
  { value: "es-US", name: "Español - Estados Unidos" },
  { value: "es-GT", name: "Español - Guatemala" },
  { value: "es-HN", name: "Español - Honduras" },
  { value: "es-MX", name: "Español - México" },
  { value: "es-NI", name: "Español - Nicaragua" },
  { value: "es-PA", name: "Español - Panamá" },
  { value: "es-PY", name: "Español - Paraguay" },
  { value: "es-PE", name: "Español - Perú" },
  { value: "es-PR", name: "Español - Puerto Rico" },
  { value: "es-DO", name: "Español - República Dominicana" },
  { value: "es-UY", name: "Español - Uruguay" },
  { value: "es-VE", name: "Español - Venezuela" },
  { name: "Euskara", value: "eu-ES" },
  { name: "Français", value: "fr-FR" },
  { name: "Galego", value: "gl-ES" },
  { name: "Hrvatski", value: "hr_HR" },
  { name: "IsiZulu", value: "zu-ZA" },
  { name: "Íslenska", value: "is-IS" },
  { value: "it-IT", name: "Italiano - Italia" },
  { value: "it-CH", name: "Italiano - Svizzera" },
  { name: "Magyar", value: "hu-HU" },
  { name: "Nederlands", value: "nl-NL" },
  { name: "Norsk bokmål", value: "nb-NO" },
  { name: "Polski", value: "pl-PL" },
  { value: "pt-BR", name: "Português - Brasil" },
  { value: "pt-PT", name: "Português - Portugal" },
  { name: "Română", value: "ro-RO" },
  { name: "Slovenčina", value: "sk-SK" },
  { name: "Suomi", value: "fi-FI" },
  { name: "Svenska", value: "sv-SE" },
  { name: "Türkçe", value: "tr-TR" },
  { name: "български", value: "bg-BG" },
  { name: "Pусский", value: "ru-RU" },
  { name: "Српски", value: "sr-RS" },
  { name: "한국어", value: "ko-KR" },
  { value: "cmn-Hans-CN", name: "中文 - 普通话 (中国大陆)" },
  { value: "cmn-Hans-HK", name: "中文 - 普通话 (香港)" },
  { value: "cmn-Hant-TW", name: "中文 - 中文 (台灣)" },
  { value: "yue-Hant-HK", name: "中文 - 粵語 (香港)" },
  { name: "日本語", value: "ja-JP" },
  { name: "Lingua latīna", value: "la" },
]
